version: "3.8"
services:
  nextjs-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-prod
    ports:
      - "8081:3000"
    restart: always
    environment:
      NODE_ENV: production
