version: "3.8"
services:
  nextjs-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-dev
    ports:
      - "8080:3000"
    restart: always
    environment:
      NODE_ENV: development
