import type { Metadata } from "next";
import "@/styles/reset.css";
import "@/styles/global.css";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Providers> {children}</Providers>
      </body>
    </html>
  );
}
