name: Next.js CI/CD with Docker Compose

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set deployment variables
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "COMPOSE_FILE=docker-compose.prod.yml" >> $GITHUB_ENV
          else
            echo "COMPOSE_FILE=docker-compose.dev.yml" >> $GITHUB_ENV
          fi

      - name: Deploy to NAS via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd prography/10th-1team-front
            git fetch --all
            git reset --hard origin/main

            docker-compose -f $COMPOSE_FILE down || true
            docker-compose -f $COMPOSE_FILE up -d --build
