# .github/workflows/storybook-cleanup.yml

name: Clean up Storybook Preview on PR close

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete preview directory via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf /volume1/docker/storybook/preview/PR-${{ github.event.pull_request.number }}
